@ControleLancamentosAPI_HostAddress = http://localhost:5117

POST {{ControleLancamentosAPI_HostAddress}}/Lancamento/
Accept: application/json
Content-Type: application/json
{
  "natureza": 2,
  "operador": "OP511",
  "descricao": "Venda Teste",
  "valor": 5222.23
}
###
