@ControleLancamentosAPI_HostAddress = http://localhost:5117

POST {{ControleLancamentosAPI_HostAddress}}/Lancamentos/
Accept: application/json

{
  "natureza": 1,
  "operador": "OP510",
  "descricao": "Venda",
  "valor": 542.23
}

###
